version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
            context: .
            dockerfile: ./build/apache/Dockerfile
    volumes:
      - ./cloud_project:/var/www/html/
    ports:
      - 80:80
      - 8000:80
    depends_on:
      - mysql_db
    networks:
            default:
                ipv4_address: 172.18.1.2

  mysql_db:
      container_name: mysql_db        
      hostname: mysql_db
      image: mysql:5.7
      restart: always
      ports:
        - 3306:3306
      environment:
          MYSQL_ROOT_PASSWORD: root
      networks:
          default:
            ipv4_address: 172.18.1.3
      volumes:
        - ./idm_users:/var/lib/mysql

  keyrock:
      image: fiware/idm:7.6.0
      container_name: keyrock
      hostname: keyrock
      depends_on: 
          - mysql_db
      ports:
          - 3005:3005
          - 3443:3443
      networks:
        default:
          ipv4_address: 172.18.1.4
      environment: 
          - IDM_DB_HOST=mysql_db
          - IDM_DB_USER=keyrock
          - IDM_DB_PASS=keyrock
          - IDM_HOST=http://localhost:3005
          - IDM_PORT=3005
          - IDM_HTTPS_ENABLED=false
          - IDM_HTTPS_PORT=3443
          - IDM_ADMIN_USER=admin
          - IDM_ADMIN_EMAIL=a@b.c
          - IDM_ADMIN_PASS=admin

  phpmyadmin:
      container_name: sql-admin
      image: phpmyadmin/phpmyadmin
      ports:
          - 8080:80
      restart: always
      environment:
        PMA_HOST: mysql_db
      depends_on:
          - mysql_db
      networks:
          default:
            ipv4_address: 172.18.1.5

  mongo:
        image: mongo:latest
        container_name: mongodb
        restart: always
        volumes:
           - ./mongo_db:/data/db
        environment:
           MONGO_INITDB_ROOT_USERNAME: admin
           MONGO_INITDB_ROOT_PASSWORD: admin
        ports: 
           - 27018:27017
        networks:
            default:
               ipv4_address: 172.18.1.6

  data-storage:
        container_name: data-storage
        hostname: data-storage
        build:
          context: .
          dockerfile: ./build/data-storage/Dockerfile
        networks:
           default:
              ipv4_address: 172.18.1.7
        expose:
          - 80

  dss-proxy:
        image: fiware/pep-proxy
        container_name: data-storage-proxy
        hostname: ds-proxy
        networks:
            default:
              ipv4_address: 172.18.1.8
        ports:
          - 4001:4001
        expose:
          - 4001
        depends_on:
          - keyrock
        environment:
          - PEP_PROXY_APP_HOST=data-storage
          - PEP_PROXY_APP_PORT=80
          - PEP_PROXY_PORT=4001
          - PEP_PROXY_IDM_HOST=keyrock
          - PEP_PROXY_HTTPS_ENABLED=false
          - PEP_PROXY_AUTH_ENABLED=false
          - PEP_PROXY_IDM_SSL_ENABLED=false
          - PEP_PROXY_IDM_PORT=3005
          - PEP_PROXY_APP_ID=--YOUR ID--
          - PEP_PROXY_USERNAME=--YOUR USERNAME--
          - PEP_PASSWORD=--YOUR PASSWORD--
          - PEP_PROXY_PDP=idm

  orion:
        image: fiware/orion
        hostname: orion
        container_name: orion
        links:
           - orion-mongo
        command: -dbhost orion-mongo -dbuser admin -dbpwd admin
        networks:
           default:
              ipv4_address: 172.18.1.9
        expose:
           - 1026

  orion-proxy:
        image: fiware/pep-proxy
        container_name: orion-proxy
        hostname: orion-proxy
        networks:
           default:
              ipv4_address: 172.18.1.10
        ports:
          - 4002:4002
        expose:
          - 4002
        depends_on:
          - keyrock
        environment:
          - PEP_PROXY_APP_HOST=orion
          - PEP_PROXY_APP_PORT=1026
          - PEP_PROXY_PORT=4002
          - PEP_PROXY_IDM_HOST=keyrock
          - PEP_PROXY_HTTPS_ENABLED=false
          - PEP_PROXY_AUTH_ENABLED=false
          - PEP_PROXY_IDM_SSL_ENABLED=false
          - PEP_PROXY_IDM_PORT=3005
          - PEP_PROXY_APP_ID=--YOUR ID--
          - PEP_PROXY_USERNAME=--YOUR USERNAME--
          - PEP_PASSWORD=--YOUR PASSWORD--
          - PEP_PROXY_PDP=idm

  orion-mongo:
        image: mongo:latest
        container_name: mongodb-orion
        restart: always
        volumes:
           - ./mongodb_orion_data/database:/data/db
        environment:
           MONGO_INITDB_ROOT_USERNAME: admin
           MONGO_INITDB_ROOT_PASSWORD: admin
        ports:
           - 27017:27017
        expose:
           - 27017
        networks:
           default:
               ipv4_address: 172.18.1.11
    
networks:
  default:
      ipam:
          config:
              - subnet: 172.18.1.0/24
  
